### ISSUE TITLE
Preparing for Linux distro packages

### ISSUE THREAD

**Issue by yan12125** [lxqt/lxqt-wayland-session#13]
As mentioned in https://github.com/lxqt/lxqt/pull/2603, it may be the time to create Linux distro packages for this repo. Some things should be checked before that can happen:

* License
* Dependencies: README says liblxqt and lxqt-session are needed. It looks like liblxqt is not used?

**Comment by stefonarch** [comment]
> . It looks like liblxqt is not used?

It is used here https://github.com/lxqt/lxqt-wayland-session/blob/master/waylandsession/CMakeLists.txt but actually those desktop files used by  display managers aren't even on weblate -which could change, having "LXQt Desktop" translated, for "LXQt (Wayland)"  it doesn't make sense to translate even. But as it is a depenendency already of `lxqt-session` we could remove it from the Readme as well.

For the license I've no clue at all, in general and as we ship slightly  modified default config files of 5 compositors.

**Comment by stefonarch** [comment]
Collecting, case it has to be used:

* lxqt-hyprland.conf: BSD 3-Clause License https://github.com/hyprwm/Hyprland/blob/main/LICENSE
* lxqt-wayfire.conf: MIT License https://github.com/WayfireWM/wayfire/blob/master/
LICENSE
* lxqt-sway.conf: MIT License
* labwc files:  GNU General Public License v2.0
* lxqt-river.conf: GNU General Public License v3.0

**Comment by yan12125** [comment]
> It is used here https://github.com/lxqt/lxqt-wayland-session/blob/master/waylandsession/CMakeLists.txt

Could you describe more? Apparently only files in this repo and a function from lxqt-build-tools are used.

> But as it is a dependency already of lxqt-session we could remove it from the Readme as well.

It's generally better to keep dependencies that are already covered, as they may no longer be covered one day.

> For the license I've no clue at all, in general and as we ship slightly modified default config files of 5 compositors.

I'm not a lawyer but I think modified files use the same license as original files, so the license for this repo will be quite complex as per the last comment.

On the other hand, I believe that for files that are not based on something else, the authors can pick whatever license they want.

**Comment by stefonarch** [comment]
> > It is used here https://github.com/lxqt/lxqt-wayland-session/blob/master/waylandsession/CMakeLists.txt
> 
> Could you describe more? Apparently only files in this repo and a function from lxqt-build-tools are used.
> 
> >

Looks like I mixed up build-tools and liblxqt, in fact.

>On the other hand, I believe that for files that are not based on something else, the authors can pick whatever license they want.

Most other is based on `lxqt-session`, so "GNU Lesser General Public License v2.1" should be fine, while the labwc icon used together with our graphics is licensed under [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) and the original Vent theme GPL 3.0.

**Comment by stefonarch** [comment]
If this PR is ok we need to add the single files.

**Comment by yan12125** [comment]
Reopening as dependencies in README should be updated as well

**Comment by stefonarch** [comment]
If we add only `lxqt-session` the bare minimum is covered, as it takes in the rest:

>Runtime dependencies are xdg-user-dirs, [liblxqt](https://github.com/lxqt/liblxqt), [qtxdg-tools](https://github.com/lxqt/qtxdg-tools) and layer-shell-qt.

-------------------
### Other compositors

Any compositor should work in general, but for taskbar support  `wlr-foreign-toplevel-management-unstable-v1` protocol support is mandatory. The line `lxqt-session && <exit_command>` is needed in the autostart section of the compositor.

### Compiling source code

Runtime dependency is [lxqt-session](https://github.com/lxqt/lxqt-session).
Additional build dependencies are CMake and optionally Git to pull latest VCS checkouts.

**Comment by yan12125** [comment]
> If we add only lxqt-session the bare minimum is covered, as it takes in the rest?

My opinion was in https://github.com/lxqt/lxqt-wayland-session/issues/13#issuecomment-2315899394:

> It's generally better to keep dependencies that are already covered, as they may no longer be covered one day.

---

Protocol requirements are also worth a mention, maybe in this repo or https://github.com/lxqt/lxqt-panel/

**Comment by stefonarch** [comment]
Added everything now.

**Comment by stefonarch** [comment]
> Protocol requirements are also worth a mention, maybe in this repo or https://github.com/lxqt/lxqt-panel/

Good point. I mentioned `wlr-foreign-toplevel-management-unstable-v1` in https://github.com/lxqt/lxqt/wiki/ConfigWaylandSettings#compositors but that's for the taskbar support only. Probably best name them all together here.

**Comment by yan12125** [comment]
Package created :) https://aur.archlinux.org/packages/lxqt-wayland-session-git

**Comment by stefonarch** [comment]
What a huge collection of optional deps :)
