### ISSUE TITLE
pure wayland without xorg

### ISSUE THREAD

**Issue by bingmatv** [lxqt/lxqt-wayland-session#30]
I tried it with pure wayland, i.e, without xorg, it couldn't start.

**Comment by stefonarch** [comment]
Please add more details: distro, setup, what happens on tty with `startlxqtwayland`, compositor used.

I did ` yay -R xorg-server sddm sddm-conf-git ` and no issue restarting the session with greetd. 

Removing `xorg-server-common` wants to remove those on arch:

```
breeze-enhanced-git-r56.aef497e-1  hikari-1:2.3.3-5  hyprland-0.44.1-1  plasma-desktop-6.2.0-1
               plasma-integration-6.2.0-1  plasma-pa-6.2.0-1  plasma-workspace-6.2.0-1  powerdevil-6.2.0-1
               river-git-0.3.5.r25.gf82b2f5-1  wayfire-git-0.9.0.r2.g43532cc4-1  wayfire-plugins-shadows-git-r79.81699f6-1
               wayfire-plugins-windecor-0.8.0-3  xdg-desktop-portal-kde-6.2.0-1  xorg-server-xephyr-21.1.13-1
               xorg-server-xvfb-21.1.13-1  xorg-xwayland-24.1.2-1  xwayland-satellite-0.4-1  xorg-server-common-21.1.13-1


```

**Comment by bingmatv** [comment]
> distro

Parabola, based on ArchLinux. Maybe the package in Parabola repo is too old?

**Comment by stefonarch** [comment]
The wayland session (will be released in a month) is not yet  in arch, it's in AUR. You need all packages from AUR.
