### ISSUE TITLE
No panel or desktop when the compositor's full path is used

### ISSUE THREAD

**Issue by knm100** [lxqt/lxqt-wayland-session#43]
After installed lxqt-wayland-session, and start lxqt(wayland) form sddm,   It looks like I login  labwc, no desktop and lxqt-panel.
I can start lxqt-session by following script file made by you( I comment out something)
[startlxqtlabwc.txt](https://github.com/user-attachments/files/17760387/startlxqtlabwc.txt)

**Comment by stefonarch** [comment]
If you try just `startlxqtwayland` from tty what errors do you get?

**Comment by knm100** [comment]
> If you try just `startlxqtwayland` from tty what errors do you get?

Please see the following log.txt
[log.txt](https://github.com/user-attachments/files/17782911/log.txt)

by the way,  black screen is beacuse I didn't install the screen background progame like swaybg.

**Comment by stefonarch** [comment]
Those are all errors of labwc. It looks like you didn't choose any compositor in "Session Settings" yet, so it should load only `lxqt-config-session` and a notification about choosing a compositor.

**Comment by knm100** [comment]
Please see the video of choosing compositor

https://github.com/user-attachments/assets/2441ded6-70d4-4766-8978-4e36111658fa

**Comment by tsujan** [comment]
> arch linux,vmware

I' be suspicious of vmware.

**Comment by stefonarch** [comment]
If you add just "labwc" in the dropdown, without searching for it? Have to look what happens with the full path in the script.

**Comment by stefonarch** [comment]
Confirmed, using full path creates this issue. Will look into it later.

**Comment by stefonarch** [comment]
It's quite simple what happened: the string `/usr/bin/labwc`  wasn't recognised as valid compositor and it fell back to default labwc with or without `~/.config/labwc/` .

**Comment by knm100** [comment]
Thanks,  Worked for me
