### ISSUE TITLE
Archlinuxarm Cannot Login To LXQT-Wayland Session

### ISSUE THREAD

**Issue by JFLim1** [lxqt/lxqt-wayland-session#46]
Updated alarm-lxqt 2.0 to lxqt-2.1.0 yesterday.
Need help on how to enter into Wayland Session in LXQT 2.1.0.

Had installed "lxqt-wayland-session" and reboot.  Selecting "LXQT Wayland" at SDDM login screen will not boot into LXQT Wayland Desktop. It will go into a loop entering "password" again and again.

 Select "LXQT Desktop" which boot into LXQT X11 Desktop.  What I noticed is that there is NO Wayland Compositor installed.  Wayland Settings indicated NO Wayland Compositor available.

How to install lxqt-labwc-session or Labwc compositor on Archlinuxarm?  Check archlinuxarm.org repo but lixq-labwc-session or labwc compositor are not available.  Are there prebuilt packages anywhere to download for archlinuxarm?  

What other archlinuxarm packages need to be installed to get LXQT Wayland working.  Reason chromium-mpp_v129 requires Wayland Session in order for the vpu hardware acceleration to work.

![image](https://github.com/user-attachments/assets/04da1046-5ff3-4f7b-bdc8-fc1092cd3387)

**Comment by stefonarch** [comment]
Install just  labwc or any other compositor. With labwc a dialog will be shown to select the compositor.
